title: Jens-Peter Joost
logo: /assets/headshot_circle.png
description: Data Scientist | AI Expert | Algorithm Engineer | Scrum Master
theme: jekyll-theme-minimal
social_links:
linkedin: jens-peter-joost